'''Version 0.35'''
from bs4 import BeautifulSoup
import requests
from collections import defaultdict


Liquid_Measurements=set(["Tbsp",
      "Tbsps",
      "bottle",
      "bottles",
      "c",
      "cs",
      "cup",
      "cups",
      "dessertspoon",
      "dessertspoons",
      "fl oz",
      "fl ozs",
      "fluid ounce",
      "fluid ounces",
      "fluid oz",
      "fluid ozs",
      "gal",
      "gallon",
      "gallons",
      "gals",
      "jar",
      "jars",
      "liter",
      "liters",
      "milliliter",
      "milliliters",
      "ml",
      "mls",
      "pint",
      "pints",
      "pt",
      "pts",
      "qt",
      "qts",
      "quart",
      "quarts",
      "tablespoon",
      "tablespoons",
      "teaspoon",
      "teaspoons",
      "tsp",
      "tsps"])
Solid_Measurements=set([
       "#",
      "#s",
      "bag",
      "bags",
      "bunch",
      "bunches",
      "can",
      "cans",
      "clove",
      "cloves",
      "cube",
      "cubes",
      "dash",
      "dashes",
      "envelope",
      "envelopes",
      "gram",
      "grams",
      "head",
      "heads",
      "inch",
      "inches",
      "kilogram",
      "kilograms",
      "lb",
      "lbs",
      "ounce",
      "ounces",
      "oz",
      "ozs",
      "package",
      "packages",
      "packet",
      "packets",
      "piece",
      "pieces",
      "pinch",
      "pinches",
      "pound",
      "pounds",
      "sheet",
      "sheets",
      "slice",
      "slices",
      "strip",
      "strips"
])
